# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     none
paginate_path: /page:num
timezone:      null

#站点基础配置
title: AwThink
subTitle: Talk is cheap,Show me the code
description: 这是 AwThink 的技术博客，它是基于 GitHub Pages 搭建起来的。在这里，AwThink 将记录工作、学习和成长中的一点一滴，并且，这也是 AwThink 对 Git 的学习和使用的一次有意义的实践。
url: http://think.awthink.net
feed: /atom.xml

#菜单配置
nav:
  - text: 主页
    url: http://awthink.net/
    icon: icon-home
    class: home
  - text: Read
    url: http://read.awthink.net
    icon: icon-reorder
    class: none
  - text: Write
    url: http://write.awthink.net
    icon: icon-book
    class: none

page:
  - text: 文章分类
    url: /category.html
    last: false

author:
  name: AwThink
